#ifndef STATES_H
#define STATES_H


enum  StatesEnum{
  STATE_START = 0,
  STATE_INIT_PINS, 
  STATE_SERIAL_INIT,
  STATE_INIT_I2C_LCD,
  STATE_INIT_FS,
  STATE_INIT_CONFIG_FILE,
  STATE_INIT_WEB_SERVER,
  STATE_READ_FS_CONFIG,
  STATE_READY,
  STATE_ERROR
} ;

#endif // STATES_H